// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctdsxhqwpabzakkcgmqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0ZHN4aHF3cGFiemFra2NnbXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDMxOTAsImV4cCI6MjA2Mjk3OTE5MH0.Uva73bbsS6g07RAaWmZz7Kf-sqEYMiQZS_odAxb6m-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});